#
#

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: username
  password: username 
  host: localhost
  database: database

test:
  adapter: sqlite3
  database: ':memory:'
  pool: 5
  timeout: 5000
  
